services:
  # Database Service
  mariadb:
    image: mariadb:10.6.7
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpass
      MYSQL_DATABASE: moodle45
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepassword
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - moodlenet

  # PHP-FPM Service
  php:
    image: php:8.1-fpm
    volumes:
      - ./moodle:/var/www/html
      - ./moodledata:/var/www/moodledata
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - moodlenet
    depends_on:
      - mariadb
    environment:
      - MOODLE_DOCKER_PHPUNIT=true
      - MOODLE_DOCKER_BEHAT=true

    # Install required PHP extensions for Moodle
    entrypoint: >
      /bin/sh -c "
      apt-get update &&
      apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev libicu-dev g++ libzip-dev libxml2-dev &&
      docker-php-ext-configure gd --with-freetype --with-jpeg &&
      docker-php-ext-configure intl &&
      docker-php-ext-install gd mysqli pdo pdo_mysql intl zip soap exif opcache &&
      pecl install xdebug &&
      apt-get clean &&
      echo 'listen = 9000' >> /usr/local/etc/php-fpm.d/zz-docker.conf &&
      php-fpm
      "

  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - "8045:80"   # HTTP
      - "8443:443"  # HTTPS
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./moodle:/var/www/html
      - ./ssl:/etc/nginx/ssl
    networks:
      - moodlenet
    depends_on:
      - php

  # Mailhog Service
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"  # Access Mailhog UI via http://localhost:8025
    networks:
      - moodlenet

volumes:
  dbdata:

networks:
  moodlenet:
